### ISSUE TITLE
I can't change the colour.

### ISSUE THREAD

**Issue by Qhaku** [cjdduarte/MDS_Time_Left#10]
Hello. I'm sorry for not being able to figure out something this simple, but for some reason I can't change the colors on the add-on. I changed the color names to the ones from this site https://www.w3schools.com/colors/colors_groups.asp, but the colors on the anki home page won't change.

**Comment by cjdduarte** [comment]
Could you provide me with the changed code with the codes for you to check?

**Comment by Qhaku** [comment]
This is the part that I modified.

 #----- Modify here (Anki 2.0) ------
    config = dict(CountTimesNew = 2, NewColor = 'SkyBlue', ReviewColor = 'Crimson', LearnColor = 'DarkRed', TotalDueColor = 'ForestGreen', TotalColor = 'Aqua')
