### ISSUE TITLE
Cards/Minute and Time Left during Review

### ISSUE THREAD

**Issue by carlos1172** [cjdduarte/MDS_Time_Left#16]
I love what you've done here. Especially the calculation about new cards taking 4 views before being "done" for the day. I'd like to see some sort of progress bar, or at least the "Time Left" and "Cards/Min" statistics on the top or bottom of my screen _while_ doing reviews. How would one go about doing that, knowing that I have never made an anki addon before?

**Comment by cjdduarte** [comment]
Hi Carlos. Thanks for the comments.
See if this addon is what you're looking for:

[Remaining time](https://ankiweb.net/shared/info/1508357010)

**Comment by carlos1172** [comment]
I'd like it to be able to show the estimate the way you calculate the estimate, which is based on cards (e.g. New cards count as x times per day), as well as cards done (studied 1000 cards in 2 hrs (7.2 s/card; therefore 1000 cards left at 7.2 s/card means 120 minutes remaining).

Sorry, I hope that made sense.

I don't know how to tweak their code to function like yours, except it's in the review screen.
