### ISSUE TITLE
Option to exclude decks/tags from stats calculation

### ISSUE THREAD

**Issue by akavi1** [cjdduarte/MDS_Time_Left#19]
Would love an option to exclude a particular deck or tag from the overall deck stats. I have some decks in my collection that have many cards due but I have no plans to keep studying them. Would be nice if cards in those decks did not add to the stats displayed.
Alternatively (and preferentially), you could do the same thing with a tag. Cards with a particular tag would be excluded from the deck stats, regardless of which deck they are in. I have some cards which I have tagged appropriately that I have no intention of studying. The deck structure is pretty complex so I don't want to move them out of their original decks. Instead, I tag them and move them into a filtered deck which I don't touch.

**Comment by cjdduarte** [comment]
I will evaluate initially by tag.

Thanks for the sugestion
