### ISSUE TITLE
Incorrect Info

### ISSUE THREAD

**Issue by MedAnki** [cjdduarte/MDS_Time_Left#2]
So to explain briefly, 
I have 
90 new cards, and 
207 review cards.
That is about
297 total cards.
My time average shown is 3.8 cards/minute
And probable time required is 77 minutes.

Now this 77 minutes is wrong because the add-on is counting new cards single time and not twice.
77 x 3.8 = 292(almost 297) and this is not an issue as this is "rounding off"

If I add new cards twice in the formula then,
[(90x2) + 207]/(avg. time) = [(90x2) + 207]/(3.8) ~ 101 mins.

So there is a difference of almost 30 mins.

Thought you should know because I love the concept of the add-on and would love to use it if this is fixed!

**Comment by cjdduarte** [comment]
Hi, I'll rate this and return. Thank you.

**Comment by Lightsout565** [comment]
I noticed this as well. Changed line 21 to

`total = new + new + lrn + due`

and it fixed the issue

**Comment by cjdduarte** [comment]
> I noticed this as well. Changed line 21 to
> 
> `total = new + new + lrn + due`
> 
> and it fixed the issue

Sorry, just to understand? Why repeat the new card twice?

You use the default setting, correct? Where a new card returns in 10 minutes being studied twice on the same day. Is this why you want to insert the new card twice?

**Comment by Lightsout565** [comment]
By default, a new card is seen twice that day before it "graduates". If I have a new card, get it right the first time, by default I will see it 10 minutes later (as you correctly pointed out). If I get it right again, that card becomes graduated and I wont see it again until whatever my "graduating interval" is set to. Doubling the "new" value is just because I have to see these cards twice that day.

**Comment by cjdduarte** [comment]
> By default, a new card is seen twice that day before it "_graduates_". If I have a new card, get it right the first time, by default I will see it 10 minutes later (as you correctly pointed out). If I get it right again 10 minutes later, that card becomes graduated and I wont see it again until whatever my "graduating interval" is set to. Doubling the "new" value is just because I have to see these New cards twice that day.

got it. I will change to leave both options. Because I use (10 1440), that would not make sense to this change. Then I will let the user choose.

**Comment by cjdduarte** [comment]
> So to explain briefly,
> I have
> 90 new cards, and
> 207 review cards.
> That is about
> 297 total cards.
> My time average shown is 3.8 cards/minute
> And probable time required is 77 minutes.
> 
> Now this 77 minutes is wrong because the add-on is counting new cards single time and not twice.
> 77 x 3.8 = 292(almost 297) and this is not an issue as this is "rounding off"
> 
> If I add new cards twice in the formula then,
> [(90x2) + 207]/(avg. time) = [(90x2) + 207]/(3.8) ~ 101 mins.
> 
> So there is a difference of almost 30 mins.
> 
> Thought you should know because I love the concept of the add-on and would love to use it if this is fixed!

Improvement implemented !!!!

**Comment by cjdduarte** [comment]
> I noticed this as well. Changed line 21 to
> 
> `total = new + new + lrn + due`
> 
> and it fixed the issue

Improvement implemented !!!!
