### ISSUE TITLE
addons21\1556734708\mds_time_left.py:46:dayCutoff is deprecated: please use 'day_cutoff'

### ISSUE THREAD

**Issue by khonkhortisan** [cjdduarte/MDS_Time_Left#22]
```
addons21\1556734708\mds_time_left.py:46:dayCutoff is deprecated: please use 'day_cutoff'
```
https://github.com/cjdduarte/MDS_Time_Left/blob/b5709e75046157efe38dfb1ce1f3533043941e30/mds_time_left.py#L46

 - OS: Windows 10
 - Anki Version 2.1.55 (35431c59)⁩

**Comment by cjdduarte** [comment]
> ```
> addons21\1556734708\mds_time_left.py:46:dayCutoff is deprecated: please use 'day_cutoff'
> ```
> 
> https://github.com/cjdduarte/MDS_Time_Left/blob/b5709e75046157efe38dfb1ce1f3533043941e30/mds_time_left.py#L46
> 
> * OS: Windows 10
> * Anki Version 2.1.55 (35431c59)⁩

Hi, I will test here and update.
Thanks.

**Comment by cjdduarte** [comment]
Tanks
