### ISSUE TITLE
Delete "Average" and "X minutes more"

### ISSUE THREAD

**Issue by Okosh50** [cjdduarte/MDS_Time_Left#25]
Hi! 

Love what you've done with the add-on, but I wanted to make mine cleaner. Prior to the most recent update, I was able to delete the "Average" cards/min section as well as the "X minutes more" but now I haven't been able to delete the right code as I continually corrupt it. Can you help with this? Thanks!

**Comment by cjdduarte** [comment]
This is the source code before the modification. Could you change it to the way it's useful?

[https://github.com/cjdduarte/MDS_Time_Left/blob/549804d238f5417105ba5f4dffd9c89f068bfbad/mds_time_left.py](OLD)

Send it back to me, and depending on it, I'll adjust the new version to how you want it.
Can you modify and send it back to me here?"

**Comment by Okosh50** [comment]
Thank you! 

I deleted the following lines, which were lines 97-100 on my coding software:

        + "<span style='white-space:nowrap;'>" + _("Average") \
        + ":<br> " + _("%.01f") % (speed) + "&nbsp;" + (_("Cards") + "/" + _("Minutes").replace("s", "")).lower()  \
        + "</span><br><br>" \
        + str(ngettext("%s minute.", "%s minutes.", minutes) % (minutes)).replace(".", "") + "&nbsp;" + _("More").lower() \

**Comment by Okosh50** [comment]
Also, I made a couple of cosmetic updates in the newest version of the code in order to:
1) Keep all the stats in 1 line (as opposed to 2 lines on the screen)
2) Make all the stats bolded with equal spacing

These are lines 73-89 for your newest update:
 buf = generate_style() + """
        <div style='display:table;padding-top:1.5em;'>
            <div style='display:table-cell;'> 
                {} 
                <hr>
                &nbsp;{}:&nbsp; <b class='new-color'> {} </b> 
                &nbsp;{}:&nbsp; <b class='learn-color'> {} </b> 
                &nbsp;{}:&nbsp; <b class='review-color'> {} </b> 
                &nbsp;{}:&nbsp; <b class='totaldue-color'> {} </b>
                &nbsp;{}:&nbsp; <b class='total-color'> {} </b>
            </div>
            <div style='display:table-cell;vertical-align:middle;padding-left:2em;'>
                {}: <br> {}
                <br><br>
                {} {}
            </div>
        </div>

**Comment by cjdduarte** [comment]
I will evaluate here and return

**Comment by cjdduarte** [comment]
> 



> Thank you!
> 
> I deleted the following lines, which were lines 97-100 on my coding software:
> 
> ```
>     + "<span style='white-space:nowrap;'>" + _("Average") \
>     + ":<br> " + _("%.01f") % (speed) + "&nbsp;" + (_("Cards") + "/" + _("Minutes").replace("s", "")).lower()  \
>     + "</span><br><br>" \
>     + str(ngettext("%s minute.", "%s minutes.", minutes) % (minutes)).replace(".", "") + "&nbsp;" + _("More").lower() \
> ```

I will evaluate if I leave this part optional also in a future version. Thanks.
