### ISSUE TITLE
not showing studied x cards in x time today (x s/card)

### ISSUE THREAD

**Issue by salmanuc** [cjdduarte/MDS_Time_Left#26]
title says it all
![64](https://github.com/cjdduarte/MDS_Time_Left/assets/138794113/ca0d713f-de64-4a89-8621-cd9d0b087845)

**Comment by cjdduarte** [comment]
Hi. I didn't understand your request

**Comment by salmanuc** [comment]
minimal theme addon was the culprit, sorry for disturbing you. thanks for the reply though
