### ISSUE TITLE
Anki 23.12beta3 issue not starting with this plugin

### ISSUE THREAD

**Issue by mazencamper** [cjdduarte/MDS_Time_Left#27]
![Screenshot 2023-12-21 142541](https://github.com/cjdduarte/MDS_Time_Left/assets/64913600/d91696c6-5d10-4972-9f9a-291e56cee645)

anki log:

Anki 23.12 (edd38ca0)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22621

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 265, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 530, in loadProfile
  File "aqt.main", line 1068, in maybe_auto_sync_on_open_close
  File "aqt.main", line 1063, in _sync_collection_and_media
  File "aqt.sync", line 128, in sync_collection
  File "aqt.taskman", line 108, in with_progress
  File "aqt.taskman", line 69, in run_in_background
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 170, in success
  File "aqt.deckbrowser", line 184, in __renderPage
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
TypeError: renderStats() got multiple values for argument '_old'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AJT Merge Notes ['1425504015', 2023-11-03T05:47, 'None', mod]
Add-on folder with readable names ['519936472', 2020-03-07T06:36, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T13:10, 'None', '']
Advanced Browser ['874215009', 2023-10-21T17:34, 'None', '']
Advanced Review Bottom Bar ['1136455830', 2023-11-17T14:57, 'None', mod]
Anki Simulator ['817108664', 2023-11-06T20:26, 'None', mod]
AnkiWebView Inspector ['31746032', 2023-06-27T22:26, 'None', '']
Automatically flip cards 2 ['1226543617', 2023-03-12T16:54, 'None', mod]
Automatically rebuild filtered deck ['1997713323', 2021-07-18T18:18, 'None', '']
Batch Editing ['291119185', 2023-10-26T03:38, 'None', '']
Card Info During Review ['2179254157', 2023-10-19T05:58, 'None', '']
Clickable Tags v20 ['1739176371', 2022-01-31T01:58, 'None', '']
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T18:06, 'None', '']
Countdown To Events and Exams ['1143540799', 2022-06-27T14:50, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T04:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T12:17, 'None', mod]
Deck name in title 21 ['699175524', 2019-06-01T04:05, 'None', '']
Delay Overdue Cards ['43919973', 2020-08-17T01:10, 'None', '']
Edit Field During Review Cloze ['385888438', 2023-11-01T07:53, '6.17', mod]
Export in CSV format ['1478130872', 2019-01-21T21:21, 'None', '']
FSRS4Anki Helper ['759844606', 2023-12-18T19:18, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T14:47, 'None', '']
Flag label ['671965183', 2023-03-22T11:44, 'None', '']
Google Translate ['1536291224', 2023-11-01T23:25, 'None', mod]
Google Translate ['1536291225', 2023-11-01T23:25, 'None', mod]
Google Translate ['1536291226', 2023-11-01T23:25, 'None', mod]
Google Translate ['1536291227', 2023-11-01T23:25, 'None', mod]
Google Translate ['1536291228', 2023-11-01T23:25, 'None', mod]
Google Translate ['1536291229', 2023-11-01T23:25, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T22:17, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2023-11-29T17:03, 'None', mod]
Media Exporter ['567329012', 2023-10-09T02:40, 'None', '']
More Decks Stats and Time Left ['1556734708', 2023-09-24T17:08, 'None', '']
More Overview Stats 21 ['738807903', 2021-07-30T22:13, 'None', '']
Progress Bar cards done cards left secondscard time spentleft and ETA ['1097423555', 2023-10-02T11:05, 'None', '']
Quick tagging 21 ['304770511', 2020-02-11T09:17, 'None', mod]
Remove Duplicate Cards ['95590040', 2021-05-05T21:12, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T04:43, 'None', '']
Session Timer ['1287298831', 2020-06-30T19:35, 'None', '']
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T14:24, 'None', '']
Take a Break ['1065458898', 2021-02-20T14:40, 'None', '']
Toggle Tags via ReviewerEditorBrowser Context Menu ['2088508994', 2019-01-01T02:50, 'None', '']
True Retention ['613684242', 2017-11-19T23:43, 'None', '']
add-on dialog searchfilter bar ['561945101', 2023-10-18T19:22, 'None', '']
extended editor for field for tables searchreplace ['805891399', 2023-07-31T17:12, 'None', mod]
when is next learning card due today due ['563204849', 2021-12-06T18:06, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 1065458898 1097423555 111623432 1136455830 1143540799 1210908941 1226543617 1287298831 1425504015 1478130872 1536291224 1536291225 1536291226 1536291227 1536291228 1536291229 1556734708 1739176371 1771074083 1997713323 2088508994 2179254157 225180905 24411424 291119185 304770511 31746032 385888438 43919973 46611790 519936472 561945101 563204849 567329012 594329229 613684242 671965183 699175524 738807903 744725736 759844606 805891399 817108664 874215009 95590040

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Table ['1237621971', 2023-06-18T14:37, 'None', mod]
Add note id ['1672832404', 2020-12-06T13:44, 'None', '']
Anki Excel Sync ['1832015432', 2021-01-28T06:53, 'None', '']
AnkiDiscord - Discord integration for Anki ['1133851639', 2020-01-14T04:53, 'None', '']
AnkiRestart ['237169833', 2023-09-18T00:10, 'None', mod]
Auto Advance automatically show answer  flip card  audio play repeat  speed ['1747534155', 2019-11-22T07:57, 'None', '']
Automatic Scoring sets the default grade easy good hard again based on time ['1765221856', 2020-05-04T09:21, 'None', '']
Change cards decks prefix ['1262882834', 2019-02-17T12:29, 'None', '']
Edit cards template with python and a domain specific language ['1159566613', 2020-03-09T10:57, 'None', '']
Editor Live Preview ['1960039667', 2023-11-05T18:06, 'None', '']
Enhanced Cloze for Anki 21 ['1990296174', 2023-09-10T21:48, 'None', '']
External Note Editor for the Browser ['1996266159', 2020-03-31T23:59, 'None', '']
Keep card displayed in reviewer until it is modified ['1894745652', 2020-01-24T04:22, 'None', '']
Language Keyboard Auto-switch ['1606509029', 2022-10-22T10:01, 'None', mod]
Leaderboard ['41708974', 2023-01-15T13:53, 'None', '']
Memory Status Bar and Stats ['1582352817', 2023-02-28T20:04, 'None', '']
Minimize to tray ['85158043', 2023-11-26T22:18, 'None', '']
Quick Colour Changing ['2491935955', 2023-10-19T06:15, 'None', mod]
Reverso importer ['2060267742', 2020-09-30T11:11, 'None', '']
Review First ['181194973', 2019-03-06T20:47, 'None', '']
Simple Timer and Stopwatch for Anki 21 ['1423272642', 2018-01-25T02:03, 'None', '']
Special Fields ['1102281552', 2023-11-01T19:37, 'None', '']
Study Time Stats ['1247171202', 2023-09-28T19:30, 'None', '']
Ze Add Note Id ['886709118', 2021-03-02T23:06, 'None', '']
auto rate typed answer ['1836029849', 2021-12-06T17:54, 'None', '']
hjp-linkmaster   mind graph roaming reviewer bilinker ['1420819673', 2023-04-11T16:27, 'None', '']

**Comment by cjdduarte** [comment]
I am aware of the bug and am working to fix it as soon as possible.

**Comment by cjdduarte** [comment]
The RC1 version of Anki has been released, and the addon is now functional in this update.
