### ISSUE TITLE
Use previous data to estimate "minutes more"

### ISSUE THREAD

**Issue by synlestidae** [cjdduarte/MDS_Time_Left#28]
Hello, this is a handy plugin! Thank you for making it.

I wonder if it is possible that the "minutes more" could be estimated using data from the last day of reviews, or a weighted average of last days? When I open the app, `minutesMore ~= numberOfReviews` i.e. a minute each. I would be happy to take a look at the code and work out how to implement it (no Anki experience but I know Python)

<img width="692" alt="image" src="https://github.com/user-attachments/assets/7b59e948-aedb-45d1-b3a6-445fa7e74ace">

**Comment by cjdduarte** [comment]
Thank you for the suggestion
it's an interesting idea. 
I'll evaluate this improvement.

**Comment by cjdduarte** [comment]
Implemented. Feel free to check it out!

**Comment by synlestidae** [comment]
Thanks very much, that's cool you implemented that quick.

I reinstalled the add on and the screenshot below is from this morning before doing any cards. I don't think I am getting the result you'd expect

<img width="600" alt="Screenshot 2024-08-24 at 7 41 30 AM" src="https://github.com/user-attachments/assets/f9425bee-a48b-4099-9aeb-9642de656ea0">

**Comment by cjdduarte** [comment]
Did you by any chance modify the parameter shown in the screenshot?

![image](https://github.com/user-attachments/assets/9b35cd13-7d87-4151-ad0e-dab9f748af59)

**Comment by synlestidae** [comment]
Thank you, I didn't check the settings or docs. I adjusted it and got the result I expect:

<img width="626" alt="image" src="https://github.com/user-attachments/assets/be37ce7c-7fba-4816-8888-159a952171c8">
