### ISSUE TITLE
improper dating

### ISSUE THREAD

**Issue by MasonAPatel** [cjdduarte/MDS_Time_Left#4]
![image](https://user-images.githubusercontent.com/59284337/71516911-30997400-2871-11ea-9946-0585944e48f7.png)
So currently it's 12/27/2019 and the statistic says done in 7 days but the date given is a little over 3 months away

**Comment by cjdduarte** [comment]
This information is not from my addon.
It's from this: https://ankiweb.net/shared/info/738807903
