### ISSUE TITLE
Can't change CountTimesNew

### ISSUE THREAD

**Issue by spectre008** [cjdduarte/MDS_Time_Left#7]
https://user-images.githubusercontent.com/61936843/77224288-369fa800-6b75-11ea-8b65-1f6790f28ac5.png
I changed CountTimesNew = n and there was a mistake. What should I do?

**Comment by cjdduarte** [comment]
"n" is a mathematical notation. You must enter a numeric value (ex: 1, 2, 3, 4, 5 ..... 9).

**Comment by spectre008** [comment]
If I have, for instance, 1 10 120 180 240, should I enter n=5?
ty for help)

**Comment by cjdduarte** [comment]
Yes.
But in these settings, it will take you about 9h (spaced) to finish a card on the same day.
Just an observation

**Comment by spectre008** [comment]
I see. Thanks)

**Comment by cjdduarte** [comment]
No

**Comment by spectre008** [comment]
I have 1 card with this interval. What does it have to show in this case?

**Comment by cjdduarte** [comment]
No problem
