### ISSUE TITLE
Changing Grammar of More xx Minutes 

### ISSUE THREAD

**Issue by marencka** [cjdduarte/MDS_Time_Left#8]
Could we get this to be changed to: 

XX minutes more instead of More xx minutes? 

Just sounds and looks better. Super small tweak, I know. Thanks so much!

**Comment by cjdduarte** [comment]
OK. I will evaluate here and change.

**Comment by cjdduarte** [comment]
adjusted. Could you validate?

**Comment by marencka** [comment]
Just Updated. Looks great. Thanks so much Carlos!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cjdduarte** [comment]
;-)
